### ISSUE TITLE
Add ER Diagram .dot file to src Directory

### ISSUE THREAD

**Issue by NickDaly** [NickDaly/genome-explorer#12]
- [x] We should commit the ER diagram's source file to the src directory so we have a copy and can edit it as the project changes.

- [x] We should also create a build command that builds the image and dumps it into the bin directory.  This'd probably do:

    `neato -Tpng -Goverlap=prism src/er-diagram.dot > bin/er-diagram.png`

- [x] We should also delete the ER diagram in the project's root directory.

**Comment by bexdragon** [comment]
I posted the source file in the src directory.  I'm not sure how to do the build command, so I'll just update the image file using GraphViz whenever I change the source for now.

**Comment by NickDaly** [comment]
Run `src/createErDiagram.sh` to rebuild the ER diagram in the `bin` directory.

If you're okay with this, we can remove the diagram picture from the root directory.
