### ISSUE TITLE
Add to createDb script to create UserSNPGenotype table

### ISSUE THREAD

**Issue by bexdragon** [NickDaly/genome-explorer#16]
We need to create this table that we're adding (not from the NCBI table).  Just create it empty, and we'll have the UI add, modify, and delete records.

UserSNPGenotype(user_id: integer, snp_id: integer, unigty_id: integer)
Composite primary key:  (user_id, snp_id)

**Comment by NickDaly** [comment]
This is fixed with d8a6de4.
