### ISSUE TITLE
SNPGtyFreq table import error

### ISSUE THREAD

**Issue by bexdragon** [NickDaly/genome-explorer#17]
Need to figure this one out:  might mean I missed part of composite primary key

/dev/stdin:10000: INSERT failed: UNIQUE constraint failed: SNPGtyFreq.snp_id, SNPGtyFreq.unigty_id

**Comment by NickDaly** [comment]
This output suggests you've run the import twice, without deleting the project.sqlite database between runs.  Can you make sure to delete the database and then try running the import again?

**Comment by bexdragon** [comment]
Ah, that makes sense.  Deleting project before running creation script again worked fine.
