### ISSUE TITLE
Cache Database Files

### ISSUE THREAD

**Issue by NickDaly** [NickDaly/genome-explorer#6]
Since the dataset is huge and changes rarely (tens of GB, not hundreds of KB, with changes annually), we shouldn't download the complete dataset every time we rebuild the database.

We should instead:

1. Download the individual zipped tables, if there have been any updates since the last time, or if they don't exist. (wget -N)
2. Import them from those files.

**Comment by bexdragon** [comment]
I'm also debating if the bigger tables are worth loading in their entirety.  For those we might want to only load a certain number of lines, or parse out the lines we want based on what Mark's 23andme data points to.

**Comment by NickDaly** [comment]
Right now, we're [downloading entire tables](https://github.com/NickDaly/genome-explorer/blob/master/src/createDb.sh#L5).  We can cut it off at 10,000 lines or some useful value, but given that we're dealing with millions of data points, the value will probably still have to be huge to start showing useful relationships between the tables.

Caching the tables is an easy way to capture all the relationships, if you don't mind spending a few dozen GB on the data files.

**Comment by NickDaly** [comment]
Resolved with 3d5e893: we now cache SNP files and update them when new versions are released.
